all:
  hosts:
    node1:
      ansible_host: 23.88.88.103
      ip: 23.88.88.103
      access_ip: 23.88.88.103
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
